name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.16.0
      
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Dependecies
        run: npm ci
        
      - name: Run ESLint
        run: |
           # Disable ESLint for this workflow
           # eslint-disable-next-line no-console
           echo "ESLint is disabled for this workflow" 
           # npm run lint 
           
      # - name: Build
      #   run: npm run build
        
      # - name: Save version
      #   id: version
      #   run: echo ::set-output name=tag::$(echo $(node -p -e "require('./package.json').version"))
        
      # - name: Increase version
      #   run: npm version patch
        
      # - name: Push new version
      #   run: git push
      
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        
      - name: Build & push dev image
        run: |
          SHA=$(git rev-parse --short HEAD)
          IMAGE_TAG=dev-$SHA
          docker build . -t adenli/ntserver:$IMAGE_TAG
          docker push adenli/ntserver:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # 6️⃣ Checkout the GitOps repo
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: adenali20/expense-tracker-gitops
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: gitops


      # 7️⃣ Update the image tag in the manifest
      - name: Update image tag in GitOps repo
        run: |
          cd gitops/environments/dev/xp-tracker-web
          sed -i "s|adenli/ntserver:.*|adenli/ntserver:${IMAGE_TAG}|" deployment-service.yml

      # 8️⃣ Commit and push the change
      - name: Commit and push changes
        run: |
          cd gitops
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update dev image tag to ${IMAGE_TAG}"
          git push origin main